apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  labels:
    app: frontend-ui
spec:
  selector:
    app: frontend-ui
  ports:
    - name: http
      protocol: TCP
      port: 5173
      targetPort: http
