apiVersion: v1
kind: ConfigMap
metadata:
  name: flight-service-config
  labels:
    app: flight-service
data:
  QUARKUS_HTTP_PORT: "8082"
  MYSQL_JDBC_URL: "jdbc:mysql://mysql-flight:3306/flight_booking"
  MYSQL_USER: "root"
