apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  labels:
    app: customer-service
data:
  PORT: "8084"
  APP_ENV: "dev"
  MONGODB_HOST: "mongodb-customer"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "customerdb"
  MONGODB_USER: "admin"
