spring:
  application:
    name: authservice
  profiles:
    default: dev

server:
  port: ${PORT:8081}

authservice:
  active-env: ${APP_ENV:dev}
  app-base-url: ${AUTH_APP_BASE_URL:http://localhost:8081}
  public-client:
    realm: ${KEYCLOAK_PUBLIC_REALM:skyfly-public}
    client-id: ${KEYCLOAK_CLIENT_ID_PUBLIC:skyfly-public-web}
    client-secret: ${KEYCLOAK_CLIENT_SECRET_PUBLIC:}
    redirect-uri: ${PUBLIC_REDIRECT_URI:http://localhost:5173/auth/google/callback}
    google-idp-alias: ${GOOGLE_IDP_ALIAS:google}
  corp-client:
    realm: ${KEYCLOAK_CORP_REALM:skyfly-corp}
    client-id: ${KEYCLOAK_CLIENT_ID_CORP:skyfly-corp-web}
    client-secret: ${KEYCLOAK_CLIENT_SECRET_CORP:}
    redirect-uri: ${CORP_REDIRECT_URI:http://localhost:5173/corp/auth/callback}
  keycloak:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8080}

---
spring:
  config:
    activate:
      on-profile: dev

authservice:
  prod-strict-config: false

---
spring:
  config:
    activate:
      on-profile: prod

authservice:
  prod-strict-config: true
