apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  platform: skyfly-flight-booking
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml

# Skyfly microservices
  - auth-service
  - flight-service
  - booking-service
  - customer-service
  - payment-service

# Skyfly UI
  - frontend-ui

namespace: skyfly
