apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  PORT: "8081"
  APP_ENV: "dev"
  AUTH_APP_BASE_URL: "http://auth-service:8081"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_PUBLIC_REALM: "skyfly-public"
  KEYCLOAK_CORP_REALM: "skyfly-corp"
  KEYCLOAK_CLIENT_ID_PUBLIC: "skyfly-public-web"
  KEYCLOAK_CLIENT_ID_CORP: "skyfly-corp-web"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-auth:5432/authdb"
  SPRING_DATASOURCE_USERNAME: "auth_user"
